// Auto-generated Google Business Profile Local SEO Location Configuration
export const gbpLocation = {
  storeName: "After Dark Cannabis",
  domain: "afterdarkcannabis.com",
  city: "York",
  province: "ON",
  country: "CA",
  slug: "weed-dispensary-york",
  address: "1664 Jane St, York, ON M9N 2S1",
  streetAddress: "1664 Jane St",
  postalCode: "M9N 2S1",
  phone: "(416) 302-8127",
  phoneIntl: "+14163028127",
  neighborhood: "Jane Street / York",
  nearbyAreas: ["Jane Street", "Weston", "Mount Dennis", "Keelesdale", "Eglinton West", "York", "Black Creek", "Trethewey Drive"],
  products: [
    "Flower",
    "Pre-rolls",
    "Edibles",
    "THC vapes",
    "Concentrates",
    "Shatter",
    "CBD oils",
    "Accessories"
  ],
  menuUrl: "/",
  directionsUrl: "",
  mapEmbedUrl: "",
  latitude: "43.6989",
  longitude: "-79.4975",
  hours: ["Open 24 Hours"],
  seoTitle: "After Dark Cannabis | Weed Dispensary in York",
  metaDescription: "After Dark Cannabis is a local weed dispensary in York offering flower, pre-rolls, edibles, vapes, concentrates, CBD, and service for adults 19+.",
  localLandmarks: ["Jane Street", "Weston", "Mount Dennis"],
  introVariant: "Welcome to After Dark Cannabis, your premier weed dispensary in York situated right on 1664 Jane St. We are dedicated to providing adults 19+ with top-tier weed, premium cannabis flower, pre-rolls, edibles, THC vapes, concentrates, and CBD products. If you are looking for a trusted cannabis store near Jane Street / York or a weed shop near Weston, stop by today to consult with our knowledgeable staff.",
  neighborhoodDescription: "Located in the vibrant Jane Street / York district, our cannabis store fits right into this active and historic community, surrounded by local retail shops and convenient transit links.",
  parkingNote: "Convenient street parking is available along Jane Street and surrounding side streets",
  transitNote: "Accessible by local TTC routes around Jane Street and nearby York neighborhoods.",
  sectionTitle: "Serving Customers Near Jane Street and York"
};
