// Auto-generated Google Business Profile Local SEO Location Configuration
export const gbpLocation = {
  storeName: "After Dark Cannabis",
  domain: "afterdarkcannabis.com",
  city: "York",
  province: "ON",
  country: "CA",
  slug: "weed-dispensary-york",
  address: "1664 Jane Street, York, ON M9N 2S1",
  streetAddress: "1664 Jane Street",
  postalCode: "M9N 2S1",
  phone: "+1 (437) 524-9344",
  phoneIntl: "+14375249344",
  neighborhood: "Jane Street / York",
  nearbyAreas: ["Jane Street", "Weston", "Mount Dennis", "Keelesdale", "Eglinton West", "York", "Black Creek", "Trethewey Drive"],
  products: [
    "Flower",
    "Pre-rolls",
    "Edibles",
    "THC vapes",
    "Concentrates",
    "Shatter",
    "CBD oils",
    "Accessories"
  ],
  menuUrl: "/",
  directionsUrl: "https://www.google.com/maps/dir/?api=1&destination=1664+Jane+Street,+York,+ON+M9N+2S1",
  mapEmbedUrl: "https://maps.google.com/maps?q=1664+Jane+Street,+York,+ON+M9N+2S1&z=16&output=embed",
  latitude: "43.7020642",
  longitude: "-79.5038822",
  hours: ["Open 24 Hours"],
  seoTitle: "Jane Street York Weed Dispensary | After Dark Cannabis",
  metaDescription: "Walk-in York dispensary at 1664 Jane Street. Open 24/7. Flower from $3/g, vapes, edibles, concentrates. Call +1 (437) 524-9344. Adults 19+.",
  localLandmarks: ["Jane Street", "Weston", "Mount Dennis"],
  introVariant: "After Dark Cannabis is open 24 hours at 1664 Jane Street in York. Adults 19+ can browse flower tiers, pre-rolls, edibles, THC vapes, concentrates, CBD products, and other menu categories. Use the homepage for visit information and the menu for current item details.",
  neighborhoodDescription: "Located in the vibrant Jane Street / York district, our cannabis store fits right into this active and historic community, surrounded by local retail shops and convenient transit links.",
  parkingNote: "Convenient street parking is available along Jane Street and surrounding side streets",
  transitNote: "Accessible by local TTC routes around Jane Street and nearby York neighborhoods.",
  sectionTitle: "Serving Customers Near Jane Street and York"
};
